package org.example.checkspellcheck;

import javax.xml.ws.WebFault;

@WebFault(faultBean="org.example.messages.CheckSpellcheckFaultType",
  targetNamespace="http://www.example.org/messages", name="checkSpellcheckFault")
public class CheckSpellcheckFault
  extends Exception
{
  private org.example.messages.CheckSpellcheckFaultType faultInfo;

  public CheckSpellcheckFault(String message,
                              org.example.messages.CheckSpellcheckFaultType faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public CheckSpellcheckFault(String message,
                              org.example.messages.CheckSpellcheckFaultType faultInfo,
                              Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public org.example.messages.CheckSpellcheckFaultType getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(org.example.messages.CheckSpellcheckFaultType faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)
